// @ts-check
import { defineConfig } from 'astro/config';

export default defineConfig({
  site: 'https://yallakaishi.com',
  // Directory-style output + explicit trailing slashes: GitHub Pages serves
  // `/services/index.html` for `/services/` without an extra hop, and every
  // internal URL generated by `localUrl()` already ends in `/`.
  trailingSlash: 'always',
  compressHTML: true,
  build: {
    format: 'directory',
    inlineStylesheets: 'auto',
  },
  vite: {
    build: {
      assetsInlineLimit: 2048,
    },
  },
});
